export enum ScreenName {
    WELCOME_SCREEN = 'WELCOME_SCREEN',
    SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
    SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
    SIGN_OUT_SCREEN = 'SIGN_OUT_SCREEN',
    MANAGE_SCREEN = 'MANAGE_SCREEN',
    DISCOVER_SCREEN = 'DISCOVER_SCREEN',
    LEARN_SCREEN = 'LEARN_SCREEN',
    PROGRESS_SCREEN = 'PROGRESS_SCREEN',
    MORE_SCREEN = 'MORE_SCREEN'
}