export const BottomTabIds = {
    CONTAINER: 'BOTTOM_BAR_CONTAINER',
    MANAGE_BTN: 'MANAGE_BTN',
    DICOVER_BTN: 'DISCOVER_BTN',
    LEARN_BTN: 'LEARN_BTN',
    PLAY_BTN: 'PLAY_BTN',
    PROGRESS_BTN: 'PROGRESS_BTN',
    MORE_BTN: 'MORE_BTN'
}